"""Unit checks for controls.py — the steering-vector control directions.

These tests encode the scientific claims each control must satisfy:
  - random_direction is unit-norm, seeded, deterministic;
  - matched_norm_random matches the reference norm tightly and is ~orthogonal in
    expectation (cosine ≈ 0 in high dimension);
  - shuffled_label_vector on strongly-separated data is WEAKER (lower alignment
    to the true DiffMean) than the true DiffMean is to itself;
  - extraction_stability is near 1.0 on clean separated data and low/uncertain
    on pure noise.
"""

import numpy as np

from steering.controls import (
    extraction_stability,
    matched_norm_random,
    random_direction,
    shuffled_label_vector,
)
from steering.extract import cosine, diffmean_vector


def _planted_set(dim=64, n=60, planted_axis=3, gap=4.0, noise=0.3, seed=0):
    """pos clusters at +gap along planted_axis, neg at -gap; isotropic noise."""
    rng = np.random.default_rng(seed)
    direction = np.zeros(dim)
    direction[planted_axis] = 1.0
    pos = rng.normal(0, noise, size=(n, dim)) + gap * direction
    neg = rng.normal(0, noise, size=(n, dim)) - gap * direction
    return pos, neg, direction


# --------------------------------------------------------------------------- #
# random_direction
# --------------------------------------------------------------------------- #
def test_random_direction_is_unit():
    v = random_direction(128, seed=0)
    assert abs(float(np.linalg.norm(v)) - 1.0) < 1e-5
    assert v.dtype == np.float32


def test_random_direction_scales_to_norm():
    v = random_direction(128, norm=7.5, seed=1)
    assert abs(float(np.linalg.norm(v)) - 7.5) < 1e-4


def test_random_direction_deterministic_and_seed_sensitive():
    a = random_direction(64, seed=0)
    b = random_direction(64, seed=0)
    c = random_direction(64, seed=1)
    np.testing.assert_array_equal(a, b)  # same seed -> identical
    assert cosine(a, c) < 0.9  # different seed -> different direction


# --------------------------------------------------------------------------- #
# matched_norm_random
# --------------------------------------------------------------------------- #
def test_matched_norm_random_matches_reference_norm():
    rng = np.random.default_rng(0)
    ref = rng.normal(size=512).astype(np.float32) * 3.3
    v = matched_norm_random(ref, seed=0)
    assert abs(float(np.linalg.norm(v)) - float(np.linalg.norm(ref))) < 1e-5


def test_matched_norm_random_orthogonal_in_high_dim():
    # In high dimension a random direction is ~orthogonal to any fixed vector
    # (E[|cos|] ~ sqrt(2/(pi*dim)) -> tiny). Use a reference NOT generated by
    # default_rng so no control seed can collide with the reference's own draw.
    ref = np.linspace(-1.0, 1.0, 4096).astype(np.float32)
    cosines = [abs(cosine(matched_norm_random(ref, seed=s), ref)) for s in range(20)]
    assert np.mean(cosines) < 0.05, f"expected near-orthogonal, mean |cos|={np.mean(cosines)}"


# --------------------------------------------------------------------------- #
# shuffled_label_vector — the KEY scientific check
# --------------------------------------------------------------------------- #
def test_shuffled_label_vector_is_weaker_than_true_diffmean():
    pos, neg, _ = _planted_set(dim=64, n=80, gap=5.0, noise=0.3, seed=0)
    true_dm = diffmean_vector(pos, neg)
    self_align = cosine(true_dm, true_dm)  # == 1.0 by definition

    # The key scientific check: destroying the labels collapses the recovered
    # direction. Two faces of "weaker":
    #   (a) SIGNED alignment to the true direction averages ~0 (the random split
    #       has no consistent relationship to the real concept axis) << 1.0;
    #   (b) the shuffled vector's magnitude is far smaller (the between-group
    #       mean gap vanishes when labels are random).
    aligns = [cosine(shuffled_label_vector(pos, neg, seed=s), true_dm) for s in range(20)]
    mean_signed_align = float(np.mean(aligns))
    assert abs(mean_signed_align) < self_align, "shuffled control must be weaker"
    assert abs(mean_signed_align) < 0.2, f"signed shuffled alignment too high: {mean_signed_align}"

    true_norm = float(np.linalg.norm(true_dm))
    shuffled_norms = [
        float(np.linalg.norm(shuffled_label_vector(pos, neg, seed=s))) for s in range(20)
    ]
    # The destroyed-label direction is an order of magnitude smaller in norm.
    assert max(shuffled_norms) < 0.3 * true_norm, (
        f"shuffled norm too large: max={max(shuffled_norms)} vs true={true_norm}"
    )


def test_shuffled_label_vector_preserves_group_sizes():
    pos, neg, _ = _planted_set(dim=32, n=50, seed=0)
    v = shuffled_label_vector(pos, neg, seed=3)
    assert v.shape == (32,)
    assert v.dtype == np.float32


# --------------------------------------------------------------------------- #
# extraction_stability
# --------------------------------------------------------------------------- #
def test_extraction_stability_high_on_clean_data():
    pos, neg, _ = _planted_set(dim=64, n=80, gap=6.0, noise=0.3, seed=0)
    res = extraction_stability(pos, neg, n_boot=200, seed=0)
    assert res["mean_cosine_to_full"] > 0.97, res
    lo, hi = res["ci95"]
    assert lo <= res["mean_cosine_to_full"] <= hi
    assert hi - lo < 0.1  # tight band on stable data


def test_extraction_stability_low_on_pure_noise():
    # No real separation: pos and neg from the SAME distribution.
    rng = np.random.default_rng(5)
    dim = 64
    noise_pos = rng.normal(0, 1.0, size=(60, dim))
    noise_neg = rng.normal(0, 1.0, size=(60, dim))
    noise_res = extraction_stability(noise_pos, noise_neg, n_boot=200, seed=0)

    # Clean reference regime for contrast.
    clean_pos, clean_neg, _ = _planted_set(dim=dim, n=60, gap=6.0, noise=0.3, seed=1)
    clean_res = extraction_stability(clean_pos, clean_neg, n_boot=200, seed=0)

    # The noise direction is markedly LESS stable than the clean direction, with
    # a much wider / lower band — the gate discriminates real structure from none.
    assert noise_res["mean_cosine_to_full"] < 0.85, noise_res
    assert noise_res["mean_cosine_to_full"] < clean_res["mean_cosine_to_full"] - 0.1
    assert noise_res["std"] > clean_res["std"], "noise band must be wider"
    assert noise_res["ci95"][0] < clean_res["ci95"][0], "noise CI reaches lower"
